export {
  selectApp,
  selectWarehouses,
  selectOrders,
  selectRoutes,
  selectLoadingWarehouse,
  selectUnloadingWarehouse,
  selectColor,
  selectIsActive,
  selectError,
  selectCenterMap,
  selectWarehouse,
  selectOrder,
  selectZoom,
  selectIsResize,
  selectMapMark,
} from 'store/selectors/selectApp';
